const QUESTIONS = [
  {
    id: "measure-001",
    category: "調味料の分量",
    important: true,
    question: "大さじ1は何ml？",
    choices: ["5ml", "10ml", "15ml", "20ml"],
    answer: "15ml",
    explanation: "大さじ1は15mlです。小さじ3杯分と同じ量です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-002",
    category: "調味料の分量",
    important: true,
    question: "小さじ1は何ml？",
    choices: ["3ml", "5ml", "10ml", "15ml"],
    answer: "5ml",
    explanation: "小さじ1は5mlです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-003",
    category: "調味料の分量",
    important: true,
    question: "大さじ1は小さじ何杯分？",
    choices: ["2杯分", "3杯分", "4杯分", "5杯分"],
    answer: "3杯分",
    explanation: "大さじ1は15ml、小さじ1は5mlなので、15÷5で3杯分です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-004",
    category: "調味料の分量",
    important: true,
    question: "小さじ1の砂糖は何g？",
    choices: ["3g", "4g", "5g", "6g"],
    answer: "3g",
    explanation: "砂糖は小さじ1で3g、大さじ1で9gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-005",
    category: "調味料の分量",
    important: true,
    question: "大さじ1の砂糖は何g？",
    choices: ["6g", "9g", "12g", "18g"],
    answer: "9g",
    explanation: "砂糖の大さじ1は9gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-006",
    category: "調味料の分量",
    important: true,
    question: "小さじ1の塩は何g？",
    choices: ["3g", "4g", "5g", "6g"],
    answer: "6g",
    explanation: "塩は小さじ1で6g、大さじ1で18gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-007",
    category: "調味料の分量",
    important: true,
    question: "大さじ1の塩は何g？",
    choices: ["9g", "12g", "15g", "18g"],
    answer: "18g",
    explanation: "塩の大さじ1は18gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-008",
    category: "調味料の分量",
    important: true,
    question: "小さじ1のみそ・しょうゆは何g？",
    choices: ["3g", "4g", "6g", "9g"],
    answer: "6g",
    explanation: "みそ・しょうゆは小さじ1で6gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-009",
    category: "調味料の分量",
    important: true,
    question: "大さじ1のみそ・しょうゆは何g？",
    choices: ["12g", "15g", "18g", "20g"],
    answer: "18g",
    explanation: "みそ・しょうゆは大さじ1で18gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-010",
    category: "調味料の分量",
    important: true,
    question: "小さじ1の油・バターは何g？",
    choices: ["3g", "4g", "5g", "6g"],
    answer: "4g",
    explanation: "油・バターは小さじ1で4gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-011",
    category: "調味料の分量",
    important: true,
    question: "大さじ1の油・バターは何g？",
    choices: ["9g", "12g", "15g", "18g"],
    answer: "12g",
    explanation: "油・バターは大さじ1で12gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "measure-012",
    category: "調味料の分量",
    important: true,
    question: "小さじ1の水・酢・酒は何g？",
    choices: ["3g", "4g", "5g", "6g"],
    answer: "5g",
    explanation: "水・酢・酒は小さじ1で5gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "rice-001",
    category: "米と水の量",
    important: true,
    question: "米1カップは何g？",
    choices: ["150g", "180g", "200g", "240g"],
    answer: "200g",
    explanation: "米1カップは200gです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "rice-002",
    category: "米と水の量",
    important: true,
    question: "水150mlは計量カップでどのくらい？",
    choices: ["1/2杯", "3/4杯", "1杯", "1と1/2杯"],
    answer: "3/4杯",
    explanation: "200mlの計量カップで150mlは3/4杯です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "safety-001",
    category: "食中毒予防",
    important: true,
    question: "食中毒予防の三原則に入らないものは？",
    choices: ["菌をつけない", "菌を増やさない", "菌を殺す", "菌を育てる"],
    answer: "菌を育てる",
    explanation: "三原則は「つけない」「増やさない」「殺す」です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "safety-002",
    category: "食中毒予防",
    important: true,
    question: "「菌をつけない」は食中毒予防の三原則に入る？",
    choices: ["入る", "入らない", "加熱だけのこと", "保存だけのこと"],
    answer: "入る",
    explanation: "手洗いや器具を分けることは、菌をつけない工夫です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "safety-003",
    category: "食中毒予防",
    important: true,
    question: "「菌を増やさない」は食中毒予防の三原則に入る？",
    choices: ["入る", "入らない", "味つけのこと", "盛りつけのこと"],
    answer: "入る",
    explanation: "低温保存などで菌が増えにくい状態にします。",
    image: "",
    imageAlt: ""
  },
  {
    id: "safety-004",
    category: "食中毒予防",
    important: true,
    question: "「菌を殺す」は食中毒予防の三原則に入る？",
    choices: ["入る", "入らない", "冷ますことだけ", "洗うことだけ"],
    answer: "入る",
    explanation: "十分な加熱は菌を殺すための大切な方法です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "nutrition-001",
    category: "栄養計算",
    important: true,
    question: "栄養計算で使う表はどれ？",
    choices: ["食品成分表", "天気図", "時刻表", "元素周期表"],
    answer: "食品成分表",
    explanation: "食品に含まれる栄養量は食品成分表を使って調べます。",
    image: "",
    imageAlt: ""
  },
  {
    id: "nutrition-002",
    category: "栄養計算",
    important: true,
    question: "食品成分表の値から1gあたりの量を出す式は？",
    choices: ["食品成分表の値÷100g", "食品成分表の値×100g", "食品成分表の値+100g", "食品成分表の値-100g"],
    answer: "食品成分表の値÷100g",
    explanation: "食品成分表は100gあたりの値なので、100で割ると1gあたりになります。",
    image: "",
    imageAlt: ""
  },
  {
    id: "knife-001",
    category: "包丁の各部位",
    important: true,
    question: "①の部分の名称はどれ？",
    choices: ["切っ先", "みね", "刃元", "柄"],
    answer: "切っ先",
    explanation: "包丁の先端部分を切っ先といいます。",
    image: "assets/knife.svg",
    imageAlt: "番号付きの包丁イラスト。1は先端、2は背、3は刃の付け根、4は柄を示す。"
  },
  {
    id: "knife-002",
    category: "包丁の各部位",
    important: true,
    question: "②の部分の名称はどれ？",
    choices: ["みね", "柄", "刃先", "切っ先"],
    answer: "みね",
    explanation: "包丁の背中側をみねといいます。",
    image: "assets/knife.svg",
    imageAlt: "番号付きの包丁イラスト。2は背中側のみねを示す。"
  },
  {
    id: "knife-003",
    category: "包丁の各部位",
    important: true,
    question: "③の部分の名称はどれ？",
    choices: ["刃元", "切っ先", "柄", "みね"],
    answer: "刃元",
    explanation: "刃の手元に近い部分を刃元といいます。",
    image: "assets/knife.svg",
    imageAlt: "番号付きの包丁イラスト。3は刃元を示す。"
  },
  {
    id: "knife-004",
    category: "包丁の各部位",
    important: true,
    question: "④の部分の名称はどれ？",
    choices: ["柄", "刃先", "みね", "切っ先"],
    answer: "柄",
    explanation: "手で持つ部分を柄といいます。",
    image: "assets/knife.svg",
    imageAlt: "番号付きの包丁イラスト。4は柄を示す。"
  },
  {
    id: "cut-001",
    category: "基本切り",
    important: true,
    question: "この切り方の名称は？",
    choices: ["輪切り", "半月切り", "いちょう切り", "みじん切り"],
    answer: "輪切り",
    explanation: "丸い材料を端から円形に切る切り方です。",
    image: "assets/cuts/ring.svg",
    imageAlt: "円形に切られた野菜のイラスト。"
  },
  {
    id: "cut-002",
    category: "基本切り",
    important: true,
    question: "この切り方の名称は？",
    choices: ["小口切り", "くし形切り", "拍子木切り", "乱切り"],
    answer: "小口切り",
    explanation: "細長い材料を端から薄く切る切り方です。",
    image: "assets/cuts/koguchi.svg",
    imageAlt: "細い野菜を端から薄く切ったイラスト。"
  },
  {
    id: "cut-003",
    category: "基本切り",
    important: true,
    question: "この切り方の名称は？",
    choices: ["半月切り", "輪切り", "色紙切り", "せん切り"],
    answer: "半月切り",
    explanation: "丸い材料を半分にして、半円形に切ります。",
    image: "assets/cuts/halfmoon.svg",
    imageAlt: "半円形に切られた野菜のイラスト。"
  },
  {
    id: "cut-004",
    category: "基本切り",
    important: true,
    question: "この切り方の名称は？",
    choices: ["いちょう切り", "輪切り", "たんざく切り", "さいの目切り"],
    answer: "いちょう切り",
    explanation: "丸い材料を4等分して、いちょうの葉のような形に切ります。",
    image: "assets/cuts/icho.svg",
    imageAlt: "いちょうの葉のような扇形に切った野菜のイラスト。"
  },
  {
    id: "cut-005",
    category: "基本切り",
    important: true,
    question: "この切り方の名称は？",
    choices: ["乱切り", "みじん切り", "輪切り", "色紙切り"],
    answer: "乱切り",
    explanation: "材料を回しながら、形をそろえすぎず大きめに切ります。",
    image: "assets/cuts/rangiri.svg",
    imageAlt: "大きさが近い不規則な形に切った野菜のイラスト。"
  },
  {
    id: "cut-006",
    category: "基本切り",
    important: true,
    question: "細かく刻む切り方は？",
    choices: ["みじん切り", "輪切り", "拍子木切り", "くし形切り"],
    answer: "みじん切り",
    explanation: "材料をとても細かく刻む切り方をみじん切りといいます。",
    image: "assets/cuts/mince.svg",
    imageAlt: "細かく刻まれた野菜のイラスト。"
  },
  {
    id: "cut-007",
    category: "基本切り",
    important: true,
    question: "細長く切る切り方は？",
    choices: ["せん切り", "さいの目切り", "輪切り", "半月切り"],
    answer: "せん切り",
    explanation: "細い線のように長く切る切り方です。",
    image: "assets/cuts/sen.svg",
    imageAlt: "細長いせん状に切った野菜のイラスト。"
  },
  {
    id: "cut-008",
    category: "基本切り",
    important: true,
    question: "さいころのように切る切り方は？",
    choices: ["さいの目切り", "たんざく切り", "ささがき", "かつらむき"],
    answer: "さいの目切り",
    explanation: "さいころのような小さな立方体に切る切り方です。",
    image: "assets/cuts/dice.svg",
    imageAlt: "さいころ状に切った野菜のイラスト。"
  },
  {
    id: "cut-009",
    category: "基本切り",
    important: true,
    question: "扇形のような形に切る切り方は？",
    choices: ["くし形切り", "色紙切り", "小口切り", "輪切り"],
    answer: "くし形切り",
    explanation: "放射状に切って、くしや扇のような形にします。",
    image: "assets/cuts/wedge.svg",
    imageAlt: "扇形に切った野菜のイラスト。"
  },
  {
    id: "cut-010",
    category: "基本切り",
    important: true,
    question: "正方形の薄い形に切る切り方は？",
    choices: ["色紙切り", "拍子木切り", "乱切り", "小口切り"],
    answer: "色紙切り",
    explanation: "薄い正方形に切る切り方です。",
    image: "assets/cuts/shikishi.svg",
    imageAlt: "薄い正方形に切った野菜のイラスト。"
  },
  {
    id: "cut-011",
    category: "基本切り",
    important: true,
    question: "短冊のような長方形に切る切り方は？",
    choices: ["たんざく切り", "みじん切り", "いちょう切り", "輪切り"],
    answer: "たんざく切り",
    explanation: "短冊のような薄い長方形に切ります。",
    image: "assets/cuts/tanzaku.svg",
    imageAlt: "短冊状に切った野菜のイラスト。"
  },
  {
    id: "cut-012",
    category: "基本切り",
    important: true,
    question: "角柱のように太めの棒状に切る切り方は？",
    choices: ["拍子木切り", "せん切り", "小口切り", "かつらむき"],
    answer: "拍子木切り",
    explanation: "拍子木のような太めの棒状に切る切り方です。",
    image: "assets/cuts/hyoshigi.svg",
    imageAlt: "太めの棒状に切った野菜のイラスト。"
  },
  {
    id: "cut-013",
    category: "基本切り",
    important: true,
    question: "ごぼうなどを鉛筆を削るように薄く切る切り方は？",
    choices: ["ささがき", "輪切り", "色紙切り", "半月切り"],
    answer: "ささがき",
    explanation: "ごぼうなどを細く薄く削るように切る方法です。",
    image: "assets/cuts/sasagaki.svg",
    imageAlt: "削るように薄く切ったごぼうのイラスト。"
  },
  {
    id: "cut-014",
    category: "基本切り",
    important: true,
    question: "大根などを薄く長くむく切り方は？",
    choices: ["かつらむき", "さいの目切り", "小口切り", "くし形切り"],
    answer: "かつらむき",
    explanation: "大根などを回しながら薄く長くむく切り方です。",
    image: "assets/cuts/katsura.svg",
    imageAlt: "大根を薄い帯状にむいたイラスト。"
  },
  {
    id: "water-001",
    category: "鍋の水の量",
    important: true,
    question: "この水の量の言い方は？",
    choices: ["ひたひたの水", "かぶるくらいの水", "たっぷりの水", "少量の水"],
    answer: "ひたひたの水",
    explanation: "材料が水面から少し出る、またはちょうど浸る程度です。",
    image: "assets/water-levels/hitahita.svg",
    imageAlt: "鍋の材料が水面から少し出ているイラスト。"
  },
  {
    id: "water-002",
    category: "鍋の水の量",
    important: true,
    question: "この水の量の言い方は？",
    choices: ["かぶるくらいの水", "ひたひたの水", "たっぷりの水", "水なし"],
    answer: "かぶるくらいの水",
    explanation: "材料が水に完全に隠れるくらいの水量です。",
    image: "assets/water-levels/kaburu.svg",
    imageAlt: "鍋の材料が水に完全に隠れているイラスト。"
  },
  {
    id: "water-003",
    category: "鍋の水の量",
    important: true,
    question: "この水の量の言い方は？",
    choices: ["たっぷりの水", "ひたひたの水", "かぶるくらいの水", "少しの水"],
    answer: "たっぷりの水",
    explanation: "材料よりかなり多い水を入れた状態です。",
    image: "assets/water-levels/tappuri.svg",
    imageAlt: "鍋に材料よりかなり多い水が入っているイラスト。"
  },
  {
    id: "pizza-001",
    category: "ピザの名前",
    important: true,
    question: "「船乗りの」という意味のピザは？",
    choices: ["マリナーラ", "ビスマルク", "カプリチョーザ", "ペスカトーレ"],
    answer: "マリナーラ",
    explanation: "マリナーラはイタリア語で「船乗りの」という意味です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "pizza-002",
    category: "ピザの名前",
    important: true,
    question: "トマト・モッツァレラ・バジルを使うピザは？",
    choices: ["マルゲリータ", "クワトロ・フォルマッジ", "ボスカイオーラ", "ビスマルク"],
    answer: "マルゲリータ",
    explanation: "マルゲリータはトマト、モッツァレラ、バジルが代表的です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "pizza-003",
    category: "ピザの名前",
    important: true,
    question: "4つのチーズを使うピザは？",
    choices: ["クワトロ・フォルマッジ", "クワトロ・スタジオーニ", "マリナーラ", "カプリチョーザ"],
    answer: "クワトロ・フォルマッジ",
    explanation: "クワトロは4、フォルマッジはチーズを表します。",
    image: "",
    imageAlt: ""
  },
  {
    id: "pizza-004",
    category: "ピザの名前",
    important: true,
    question: "「四季」という意味のピザは？",
    choices: ["クワトロ・スタジオーニ", "クワトロ・フォルマッジ", "ペスカトーレ", "ビスマルク"],
    answer: "クワトロ・スタジオーニ",
    explanation: "クワトロ・スタジオーニは「四季」という意味です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "pizza-005",
    category: "ピザの名前",
    important: true,
    question: "「木こり風」という意味のピザは？",
    choices: ["ボスカイオーラ", "マリナーラ", "マルゲリータ", "カプリチョーザ"],
    answer: "ボスカイオーラ",
    explanation: "ボスカイオーラは「木こり風」という意味です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "pizza-006",
    category: "ピザの名前",
    important: true,
    question: "卵をのせたピザは？",
    choices: ["ビスマルク", "ペスカトーレ", "マリナーラ", "クワトロ・フォルマッジ"],
    answer: "ビスマルク",
    explanation: "卵をのせたピザはビスマルクです。",
    image: "",
    imageAlt: ""
  },
  {
    id: "pizza-007",
    category: "ピザの名前",
    important: true,
    question: "魚介類・漁師風のピザは？",
    choices: ["ペスカトーレ", "ボスカイオーラ", "ビスマルク", "カプリチョーザ"],
    answer: "ペスカトーレ",
    explanation: "ペスカトーレは魚介類や漁師風を表します。",
    image: "",
    imageAlt: ""
  },
  {
    id: "pizza-008",
    category: "ピザの名前",
    important: true,
    question: "「気まぐれの」という意味のピザは？",
    choices: ["カプリチョーザ", "マリナーラ", "マルゲリータ", "クワトロ・スタジオーニ"],
    answer: "カプリチョーザ",
    explanation: "カプリチョーザは「気まぐれの」という意味です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "sashisuseso-001",
    category: "さしすせそ",
    important: true,
    question: "調味料の「さ」は？",
    choices: ["砂糖", "塩", "酢", "しょうゆ"],
    answer: "砂糖",
    explanation: "さしすせその「さ」は砂糖です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "sashisuseso-002",
    category: "さしすせそ",
    important: true,
    question: "調味料の「し」は？",
    choices: ["塩", "砂糖", "酢", "みそ"],
    answer: "塩",
    explanation: "さしすせその「し」は塩です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "sashisuseso-003",
    category: "さしすせそ",
    important: true,
    question: "調味料の「す」は？",
    choices: ["酢", "しょうゆ", "砂糖", "みそ"],
    answer: "酢",
    explanation: "さしすせその「す」は酢です。",
    image: "",
    imageAlt: ""
  },
  {
    id: "sashisuseso-004",
    category: "さしすせそ",
    important: true,
    question: "調味料の「せ」は？",
    choices: ["しょうゆ", "砂糖", "塩", "酢"],
    answer: "しょうゆ",
    explanation: "昔の表記「せうゆ」から、しょうゆを表します。",
    image: "",
    imageAlt: ""
  },
  {
    id: "sashisuseso-005",
    category: "さしすせそ",
    important: true,
    question: "調味料の「そ」は？",
    choices: ["みそ", "酢", "しょうゆ", "塩"],
    answer: "みそ",
    explanation: "さしすせその「そ」はみそです。",
    image: "",
    imageAlt: ""
  }
];
